### ISSUE TITLE
Why I set 'for 10 number' but it calculates only for 7th

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/iterators-generators-patterns#2]
https://github.com/NikitaZhukovsky/iterators-generators-patterns/blob/e18ad9ace40f218360e0f9890b69f7d9b3f98eba/Task_1/fibonachi.py#L9-L15
![Снимок экрана 2024-01-24 в 17 14 32](https://github.com/NikitaZhukovsky/iterators-generators-patterns/assets/44698380/c6349277-b8e8-4cdd-b559-bb1f679afe92)

**Comment by NikitaZhukovsky** [comment]
Because next number is 13

**Comment by NikitaZhukovsky** [comment]
Fixed it
