### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by SkrytnayaRediska** [NikitaZhukovsky/iterators-generators-patterns#4]
https://github.com/NikitaZhukovsky/iterators-generators-patterns/blob/e18ad9ace40f218360e0f9890b69f7d9b3f98eba/Task_5/calculator.py#L44-L46
![Снимок экрана 2024-01-24 в 17 26 27](https://github.com/NikitaZhukovsky/iterators-generators-patterns/assets/44698380/f7bd0b92-21b5-4d9b-baed-822e82d40b0a)

**Comment by NikitaZhukovsky** [comment]
Fixed it
